language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python setup.py test
    #- cd test; sh test_parser.sh; cd ../; if [ $* -eq 1 ]; then exit 1;
  - sh test_parser.sh
  - coverage run setup.py test
after_success:
  - coveralls
