language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python setup.py test
  - cd test; sh test_parser.sh; SHSTATUS=$?; cd ../; echo $SHSTATUS; if [ $? -ne 0 ]; then exit -1; fi
  - coverage run setup.py test
after_success:
  - coveralls
