language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python setup.py test
  - cd test; sh test_parser.sh; SHSTATUS=$?; cd ../; exit $SHSTATUS
  - coverage run setup.py test
after_success:
  - coveralls
